using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Areas.Identity.Data;
using WebApplication2.Data;
using WebApplication2.Services;
using WebApplication2.Mappings;
using WebApplication2.Middleware;
using WebApplication2.HealthChecks;
using Serilog;
using Serilog.Events;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.ResponseCompression;
using System.IO.Compression;
namespace WebApplication2
{
    public class Program
    {
        // Most of the code for this class was autogenerated by Visual Studio
        public static async Task Main(string[] args)
        {
            // Configure Serilog
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft.Hosting.Lifetime", LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .Enrich.WithProperty("Application", "AgriEnergyConnect")
                .Enrich.WithProperty("Environment", Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production")
                .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}")
                .WriteTo.File("logs/app-.txt", 
                    rollingInterval: RollingInterval.Day,
                    retainedFileCountLimit: 30,
                    fileSizeLimitBytes: 10_000_000,
                    rollOnFileSizeLimit: true,
                    outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}")
                .WriteTo.File("logs/errors/error-.txt",
                    restrictedToMinimumLevel: LogEventLevel.Error,
                    rollingInterval: RollingInterval.Day,
                    retainedFileCountLimit: 90,
                    fileSizeLimitBytes: 5_000_000,
                    rollOnFileSizeLimit: true,
                    outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}")
                .WriteTo.File("logs/performance/perf-.txt",
                    restrictedToMinimumLevel: LogEventLevel.Information,
                    rollingInterval: RollingInterval.Day,
                    retainedFileCountLimit: 14,
                    fileSizeLimitBytes: 2_000_000,
                    rollOnFileSizeLimit: true,
                    outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}")
                .CreateLogger();

            try
            {
                Log.Information("Starting web application");
                
                var builder = WebApplication.CreateBuilder(args);
                
                // Use Serilog for logging
                builder.Host.UseSerilog();
            var connectionString = builder.Configuration.GetConnectionString("WebApplication2ContextConnection") ?? throw new InvalidOperationException("Connection string 'WebApplication2ContextConnection' not found.");

            builder.Services.AddDbContext<WebApplication2Context>(options => 
            {
                options.UseSqlServer(connectionString, sqlOptions =>
                {
                    sqlOptions.CommandTimeout(30); // Set command timeout to 30 seconds
                    sqlOptions.EnableRetryOnFailure(3); // Enable retry on failure
                });
                
                // Enable sensitive data logging only in development
                if (builder.Environment.IsDevelopment())
                {
                    options.EnableSensitiveDataLogging();
                    options.EnableDetailedErrors();
                }
                
                // Disable change tracking for read-only scenarios
                options.UseQueryTrackingBehavior(QueryTrackingBehavior.TrackAll);
            });

            /*
            * This code was taken from a Youtube video
            * Uploaded by: Macro Code
            * Titled: ASP.NET Core 7.0 Role Based Authorization || How to Implement Roles Based Authorization
            * Available at: https://www.youtube.com/watch?v=VZgxKbAdbbo
            * Accessed 24 May 2023
            */
            builder.Services.AddIdentity<WebApplication2User, IdentityRole>(options => 
            {
                options.SignIn.RequireConfirmedAccount = false;
                
                // Password policy configuration
                options.Password.RequireDigit = true;
                options.Password.RequireLowercase = true;
                options.Password.RequireUppercase = true;
                options.Password.RequireNonAlphanumeric = true;
                options.Password.RequiredLength = 8;
                options.Password.RequiredUniqueChars = 1;
                
                // Account lockout configuration
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(15);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;
            })
            .AddDefaultUI()
            .AddDefaultTokenProviders()
            .AddEntityFrameworkStores<WebApplication2Context>();

            // Configure email settings
            builder.Services.Configure<EmailSettings>(builder.Configuration.GetSection("EmailSettings"));
            
            // Add AutoMapper
            builder.Services.AddAutoMapper(typeof(AutoMapperProfile));
            
            // Add custom services
            builder.Services.AddScoped<WebApplication2.Services.IAuthorizationHelperService, WebApplication2.Services.AuthorizationHelperService>();
            builder.Services.AddScoped<WebApplication2.Services.ISecurityService, WebApplication2.Services.SecurityService>();
            builder.Services.AddScoped<IEmailService, EmailService>();
            builder.Services.AddScoped<IEmailSender, EmailService>(); // For Identity UI compatibility
            builder.Services.AddScoped<IFileUploadService, FileUploadService>();
            builder.Services.AddScoped<IDataExportService, DataExportService>();
            builder.Services.AddScoped<INotificationService, NotificationService>();
            builder.Services.AddSingleton<IPerformanceLoggingService, PerformanceLoggingService>();
            builder.Services.AddScoped<ICachingService, CachingService>();
            builder.Services.AddScoped<IQueryOptimizationService, QueryOptimizationService>();
            builder.Services.AddMemoryCache(); // For caching user roles and other data
            builder.Services.AddDataProtection(); // For data encryption/decryption
            
            // Configure log cleanup service
            builder.Services.Configure<LogRetentionOptions>(options =>
            {
                options.GeneralLogs = new LogTypeOptions
                {
                    RetentionDays = 30,
                    MaxTotalSizeGB = 0.5 // 500 MB
                };
                options.ErrorLogs = new LogTypeOptions
                {
                    RetentionDays = 7,
                    MaxTotalSizeGB = 0.2 // 200 MB
                };
                options.PerformanceLogs = new LogTypeOptions
                {
                    RetentionDays = 14,
                    MaxTotalSizeGB = 0.1 // 100 MB
                };
                options.CleanupSchedule = new CleanupScheduleOptions
                {
                    IntervalHours = 24,
                    StartTime = new TimeSpan(2, 0, 0) // Run at 2 AM
                };
            });
            builder.Services.AddHostedService<LogCleanupService>();
            builder.Services.AddHostedService<SystemMetricsLoggingService>();
            
            // Add health checks
            builder.Services.AddHealthChecks()
                .AddDbContextCheck<WebApplication2Context>("database")
                .AddCheck<FileSystemHealthCheck>("filesystem")
                .AddCheck<EmailServiceHealthCheck>("email");

            // Add services to the container.
            builder.Services.AddControllersWithViews(options =>
            {
                // Configure cache profiles
                options.CacheProfiles.Add("Default", new Microsoft.AspNetCore.Mvc.CacheProfile
                {
                    Duration = 300, // 5 minutes
                    Location = Microsoft.AspNetCore.Mvc.ResponseCacheLocation.Any,
                    VaryByHeader = "User-Agent"
                });
                
                options.CacheProfiles.Add("StaticContent", new Microsoft.AspNetCore.Mvc.CacheProfile
                {
                    Duration = 3600, // 1 hour
                    Location = Microsoft.AspNetCore.Mvc.ResponseCacheLocation.Any
                });
                
                options.CacheProfiles.Add("ProductList", new Microsoft.AspNetCore.Mvc.CacheProfile
                {
                    Duration = 600, // 10 minutes
                    Location = Microsoft.AspNetCore.Mvc.ResponseCacheLocation.Any,
                    VaryByQueryKeys = new[] { "category", "search", "page" }
                });
                
                options.CacheProfiles.Add("Analytics", new Microsoft.AspNetCore.Mvc.CacheProfile
                {
                    Duration = 900, // 15 minutes
                    Location = Microsoft.AspNetCore.Mvc.ResponseCacheLocation.Any,
                    VaryByQueryKeys = new[] { "days", "type" }
                });
            });

            // Add response caching
            builder.Services.AddResponseCaching();

            // Add response compression
            builder.Services.AddResponseCompression(options =>
            {
                options.EnableForHttps = true;
                options.Providers.Add<BrotliCompressionProvider>();
                options.Providers.Add<GzipCompressionProvider>();
                options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[]
                {
                    "application/json",
                    "text/css",
                    "text/javascript",
                    "text/plain",
                    "text/html",
                    "application/javascript",
                    "image/svg+xml"
                });
            });

            // Configure compression levels
            builder.Services.Configure<BrotliCompressionProviderOptions>(options =>
            {
                options.Level = CompressionLevel.Optimal;
            });
            builder.Services.Configure<GzipCompressionProviderOptions>(options =>
            {
                options.Level = CompressionLevel.SmallestSize;
            });

            builder.Services.AddRazorPages();

            var app = builder.Build();

            // Add custom request/response logging middleware
            app.UseRequestResponseLogging();
            
            // Add Serilog request logging middleware
            app.UseSerilogRequestLogging(options =>
            {
                options.MessageTemplate = "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms";
                options.GetLevel = (httpContext, elapsed, ex) => ex != null
                    ? LogEventLevel.Error
                    : httpContext.Response.StatusCode > 499
                        ? LogEventLevel.Error
                        : LogEventLevel.Information;
                options.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>
                {
                    diagnosticContext.Set("RequestHost", httpContext.Request.Host.Value);
                    diagnosticContext.Set("RequestScheme", httpContext.Request.Scheme);
                    if (httpContext.User.Identity?.IsAuthenticated == true)
                    {
                        diagnosticContext.Set("UserName", httpContext.User.Identity.Name);
                    }
                };
            });

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            // Add security headers
            app.Use(async (context, next) =>
            {
                context.Response.Headers["X-Content-Type-Options"] = "nosniff";
                context.Response.Headers["X-Frame-Options"] = "DENY";
                context.Response.Headers["X-XSS-Protection"] = "1; mode=block";
                context.Response.Headers["Referrer-Policy"] = "strict-origin-when-cross-origin";
                context.Response.Headers["Content-Security-Policy"] = "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;";
                await next();
            });

            app.UseHttpsRedirection();

            // Add response compression (should be early in pipeline)
            app.UseResponseCompression();

            // Add response caching
            app.UseResponseCaching();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();

            app.UseAuthorization();

            app.MapRazorPages();

            app.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");
            
            // Map health check endpoints
            app.MapHealthChecks("/health", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
            {
                ResponseWriter = async (context, report) =>
                {
                    context.Response.ContentType = "application/json";
                    var response = new
                    {
                        status = report.Status.ToString(),
                        checks = report.Entries.Select(x => new
                        {
                            name = x.Key,
                            status = x.Value.Status.ToString(),
                            description = x.Value.Description,
                            data = x.Value.Data,
                            duration = x.Value.Duration.TotalMilliseconds
                        }),
                        totalDuration = report.TotalDuration.TotalMilliseconds
                    };
                    await context.Response.WriteAsync(System.Text.Json.JsonSerializer.Serialize(response));
                }
            });
            
            app.MapHealthChecks("/health/ready", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
            {
                Predicate = check => check.Tags.Contains("ready")
            });
            
            app.MapHealthChecks("/health/live", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
            {
                Predicate = _ => false
            });

            // Seeding roles into new database (whenever a new environment is created)
            /*
             * This code was taken from an online blog
             * Uploaded by: Microsoft
             * Titled: Data Seeding
             * Available at: https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding
             * Accessed 23 May 2023
            */
            using (var scope = app.Services.CreateScope())
            {
                var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();

                var roles = new[] { "Farmer", "Admin", "Support Employee" };

                foreach (var role in roles)
                {
                    if (!await roleManager.RoleExistsAsync(role))
                        await roleManager.CreateAsync(new IdentityRole(role));
                }
            }

            app.Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Application terminated unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
    }
}
