using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Areas.Identity.Data;
using WebApplication2.Data;
namespace WebApplication2
{
    public class Program
    {
        // Most of the code for this class was autogenerated by Visual Studio
        public static async Task Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            var connectionString = builder.Configuration.GetConnectionString("WebApplication2ContextConnection") ?? throw new InvalidOperationException("Connection string 'WebApplication2ContextConnection' not found.");

            builder.Services.AddDbContext<WebApplication2Context>(options => 
            {
                options.UseSqlServer(connectionString, sqlOptions =>
                {
                    sqlOptions.CommandTimeout(30); // Set command timeout to 30 seconds
                    sqlOptions.EnableRetryOnFailure(3); // Enable retry on failure
                });
                
                // Enable sensitive data logging only in development
                if (builder.Environment.IsDevelopment())
                {
                    options.EnableSensitiveDataLogging();
                    options.EnableDetailedErrors();
                }
                
                // Disable change tracking for read-only scenarios
                options.UseQueryTrackingBehavior(QueryTrackingBehavior.TrackAll);
            });

            /*
            * This code was taken from a Youtube video
            * Uploaded by: Macro Code
            * Titled: ASP.NET Core 7.0 Role Based Authorization || How to Implement Roles Based Authorization
            * Available at: https://www.youtube.com/watch?v=VZgxKbAdbbo
            * Accessed 24 May 2023
            */
            builder.Services.AddIdentity<WebApplication2User, IdentityRole>(options => 
            {
                options.SignIn.RequireConfirmedAccount = false;
                
                // Password policy configuration
                options.Password.RequireDigit = true;
                options.Password.RequireLowercase = true;
                options.Password.RequireUppercase = true;
                options.Password.RequireNonAlphanumeric = true;
                options.Password.RequiredLength = 8;
                options.Password.RequiredUniqueChars = 1;
                
                // Account lockout configuration
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(15);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;
            })
            .AddDefaultUI()
            .AddDefaultTokenProviders()
            .AddEntityFrameworkStores<WebApplication2Context>();

            // Add custom services
            builder.Services.AddScoped<WebApplication2.Services.IAuthorizationHelperService, WebApplication2.Services.AuthorizationHelperService>();
            builder.Services.AddMemoryCache(); // For caching user roles and other data

            // Add services to the container.
            builder.Services.AddControllersWithViews();

            builder.Services.AddRazorPages();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            // Add security headers
            app.Use(async (context, next) =>
            {
                context.Response.Headers.Add("X-Content-Type-Options", "nosniff");
                context.Response.Headers.Add("X-Frame-Options", "DENY");
                context.Response.Headers.Add("X-XSS-Protection", "1; mode=block");
                context.Response.Headers.Add("Referrer-Policy", "strict-origin-when-cross-origin");
                context.Response.Headers.Add("Content-Security-Policy", "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;");
                await next();
            });

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();

            app.UseAuthorization();

            app.MapRazorPages();

            app.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");

            // Seeding roles into new database (whenever a new environment is created)
            /*
             * This code was taken from an online blog
             * Uploaded by: Microsoft
             * Titled: Data Seeding
             * Available at: https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding
             * Accessed 23 May 2023
            */
            using (var scope = app.Services.CreateScope())
            {
                var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();

                var roles = new[] { "Farmer", "Admin", "Support Employee" };

                foreach (var role in roles)
                {
                    if (!await roleManager.RoleExistsAsync(role))
                        await roleManager.CreateAsync(new IdentityRole(role));
                }
            }

            app.Run();
        }
    }
}
