namespace WebApplication2.Models
{
    // Te code for this class was autogenerated by Visual Studio
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
